### ISSUE TITLE
Undefined variable $p_bugnote_id

### ISSUE THREAD

**Issue by CasN** [mantisbt-plugins/VEditor#1]
I still get the  last message ('Undefined variable $p_bugnote_id') if I add a picture by just pasting it into the note. Still the note is added

**Comment by pysiek634** [comment]
Could you provide details? (line number, stack information)
I am sure that this problem has been solved in version 1.1.0

**Comment by ghost** [comment]
You are right, think I got the update from the wrong location.
I downloaded again the plugin and it works without error message now.

Thanks a lot.
Issue can be closed.
Cas
