### ISSUE TITLE
how to activate editor plugins

### ISSUE THREAD

**Issue by ZakharchukEduard** [mantisbt-plugins/VEditor#2]
Hi.
You plugin is very much needed and helpful to me.
Thank you very much for your work.
With your plugin Mantis has been transformed for the better. ))
I have two questions:
1. Can you tell me how to activate editor plugins such as "link", "advlist", etc.? 
2. Mantis has a plugin FAQ for text editing also uses "textarea", but your plugin does not see this field. Is it possible to apply your plugin for the FAQ plugin as well?

**Comment by pysiek634** [comment]
I am glad that you like this plugin. You can enable the additional TinyMCE plugin using the configuration. Unfortunately, I haven't made a dedicated page for it yet.
You can set the configuration options of my plugin using the entries in the config_inc.php or Confguration / Configuration Report -> Create Configuration Option in Manage menu.
Look at   function config() in VEditor.php. There are many useful options there.
You should extend list in plugin_Veditor_dev_plugins option or/and reporter_plugins
In addition, you need to extend the menu to support these plugins (dev_toolbar, menubar options).

The plugin_Veditor_pages configuration option contains the names of the pages on which to run this plugin. Try to add the plugin FAQ page there. I hope this will help.

**Comment by ZakharchukEduard** [comment]
Thank you so much for your response.
I didn't expect such a quick response from you.
I will try to implement your recommendations.
I would be grateful for more detailed instructions on how to activate the "link" editor plugin.
I think if you switch it on by default - everyone will like it))).
Thanks again for your work.

**Comment by ghost** [comment]
plugin_Veditor_pages configuration option does not exist. What is required is to add an event to one of the FAQ pages and to add  an event hook and function to VEditor.php.
I will check this and inform you.

**Comment by ZakharchukEduard** [comment]
Thank you very much for your reply.
I will look forward to your instructions )).

**Comment by ZakharchukEduard** [comment]
![изображение](https://github.com/mantisbt-plugins/VEditor/assets/34164109/f99a772b-7c6b-4a3f-aec9-a3454b194ad3)
It worked!!! Thank you.

In the config() function in VEditor.php, I added "link unlink" to 'dev_toolbar' and 'reporter_toolbar' and added "link" to 'dev_plugins' and 'reporter_plugins'.
And everything worked.

**Comment by ghost** [comment]
pysiek634 was correct, it is very easy. in the same config function chnage the line
`         'pages' => ['bugnote_edit_page.php', 'view.php', 'bug_update_page.php', 'bug_report_page.php', 'bug_change_status_page.php'],`
to
`           'pages' => ['bugnote_edit_page.php', 'view.php', 'bug_update_page.php', 'bug_report_page.php', 'bug_change_status_page.php', 'faq_edit_page.php'],`

That is all, it now works when editing the FAQ page

**Comment by ZakharchukEduard** [comment]
You guys are angels.
Yes, everything worked in the FAQ plugin.
Only I added two pages to the list - 'faq_edit_page.php' and 'faq_add_page.php'

**Comment by pysiek634** [comment]
Hello, 
plugin configuration options are not available in the selection list until you use them. You can create them by using their name in Mantis configuration.

It's better not to modify the plugin code, just add the appropriate variables to the config_inc.php file.
E.g. 
`$g_plugin_VEditor_pages = ['manage_proj_edit_page.php', 'bugnote_edit_page.php', 'view.php', 'bug_update_page.php', 'bug_report_page.php', 'bug_change_status_page.php'];`

Adds support for TinyMCE for project description (manage_proj_edit_page.php page).
Similarly with other options, e.g. dev_plugins, toolbar

The use of the Link plugin has little use in Mantis, in my opinion. Mantis itself can convert links under the display. It is enough to write the address, for example, https://github.com 
Another method is to paste links from other sources. For this, of course, you need to disable the 'Paste as Text' option enabled by default.
The plugin code also allows any modification of the HTML code entered with the TinyMCE editor.

**Comment by ghost** [comment]
Works perfect now!
